
set(LIBPNG_ROOT_DIR "" CACHE PATH "libpng source root directory")
if(NOT LIBPNG_ROOT_DIR)
  message(FATAL_ERROR "libpng not found. Please set LIBPNG_ROOT_DIR.")
endif()
 
add_subdirectory("${LIBPNG_ROOT_DIR}" "libpng")
target_include_directories("png_static" PUBLIC "$<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/zlib>")
target_include_directories("png_static" PUBLIC "$<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/libpng>")
target_include_directories("png_static" PUBLIC "${LIBPNG_ROOT_DIR}")
set_property(TARGET "genfiles" PROPERTY FOLDER "third_party")
set_property(TARGET "png" PROPERTY FOLDER "third_party")
set_property(TARGET "png_static" PROPERTY FOLDER "third_party")
set_property(TARGET "pngfix" PROPERTY FOLDER "third_party")
set_property(TARGET "png-fix-itxt" PROPERTY FOLDER "third_party")
set_property(TARGET "pngimage" PROPERTY FOLDER "third_party")
set_property(TARGET "pngstest" PROPERTY FOLDER "third_party")
set_property(TARGET "pngtest" PROPERTY FOLDER "third_party")
set_property(TARGET "pngunknown" PROPERTY FOLDER "third_party")
set_property(TARGET "pngvalid" PROPERTY FOLDER "third_party")
